


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."attendance" (
    "checked_in_at" timestamp with time zone DEFAULT "now"(),
    "source" "text",
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "org_id" "uuid",
    "attendee_id" "uuid" DEFAULT "auth"."uid"(),
    "meeting_id" "uuid",
    "answers" "text"[]
);


ALTER TABLE "public"."attendance" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."attendee" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid",
    "email" "text" NOT NULL,
    "first_name" "text" NOT NULL,
    "last_name" "text" NOT NULL,
    "grad_year" "text" NOT NULL,
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "admin" boolean DEFAULT false
);


ALTER TABLE "public"."attendee" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."audit_log" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "org_id" "uuid" DEFAULT "gen_random_uuid"(),
    "action" "text",
    "target_id" "uuid" DEFAULT "gen_random_uuid"()
);


ALTER TABLE "public"."audit_log" OWNER TO "postgres";


COMMENT ON TABLE "public"."audit_log" IS 'records all actions made by officers and owners';



ALTER TABLE "public"."audit_log" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."audit_log_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."meetings" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "org_id" "uuid" NOT NULL,
    "title" "text" NOT NULL,
    "start_time" timestamp without time zone,
    "end_time" timestamp without time zone,
    "created_at" time with time zone,
    "created_by" "uuid" DEFAULT "auth"."uid"(),
    "status" boolean DEFAULT false NOT NULL,
    "questions" "text"[]
);


ALTER TABLE "public"."meetings" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."memberships" (
    "role" "text" NOT NULL,
    "status" "text",
    "created_at" "date",
    "org_id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL
);


ALTER TABLE "public"."memberships" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."organizations" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "slug" "text",
    "name" "text",
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_by" "uuid" DEFAULT "auth"."uid"()
);


ALTER TABLE "public"."organizations" OWNER TO "postgres";


ALTER TABLE ONLY "public"."memberships"
    ADD CONSTRAINT "Memberships_pkey" PRIMARY KEY ("org_id", "user_id");



ALTER TABLE ONLY "public"."attendance"
    ADD CONSTRAINT "attendance_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."attendee"
    ADD CONSTRAINT "attendee_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."audit_log"
    ADD CONSTRAINT "audit_log_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."meetings"
    ADD CONSTRAINT "meetings_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."organizations"
    ADD CONSTRAINT "organizations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."organizations"
    ADD CONSTRAINT "organizations_slug_key" UNIQUE ("slug");



ALTER TABLE ONLY "public"."attendance"
    ADD CONSTRAINT "attendance_attendee_id_fkey" FOREIGN KEY ("attendee_id") REFERENCES "public"."attendee"("id");



ALTER TABLE ONLY "public"."attendance"
    ADD CONSTRAINT "attendance_meeting_id_fkey" FOREIGN KEY ("meeting_id") REFERENCES "public"."meetings"("id");



ALTER TABLE ONLY "public"."attendance"
    ADD CONSTRAINT "attendance_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id");



ALTER TABLE ONLY "public"."audit_log"
    ADD CONSTRAINT "audit_log_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id");



ALTER TABLE ONLY "public"."audit_log"
    ADD CONSTRAINT "audit_log_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."meetings"
    ADD CONSTRAINT "meetings_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."meetings"
    ADD CONSTRAINT "meetings_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."memberships"
    ADD CONSTRAINT "memerships_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id");



ALTER TABLE ONLY "public"."memberships"
    ADD CONSTRAINT "memerships_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."organizations"
    ADD CONSTRAINT "organizations_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."attendee"
    ADD CONSTRAINT "profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



CREATE POLICY "Admin can see organizations" ON "public"."organizations" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."memberships"
  WHERE (("memberships"."user_id" = "auth"."uid"()) AND (("memberships"."role" = 'admin'::"text") OR ("memberships"."org_id" = "organizations"."id"))))));



CREATE POLICY "Enable insert for users based on user_id" ON "public"."audit_log" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."memberships"
  WHERE (("memberships"."user_id" = ( SELECT "auth"."uid"() AS "uid")) AND (("memberships"."role" = 'admin'::"text") OR (("memberships"."org_id" = "audit_log"."org_id") AND ("memberships"."role" = ANY (ARRAY['officer'::"text", 'owner'::"text"]))))))));



CREATE POLICY "Members can view attendance history" ON "public"."attendance" FOR SELECT TO "authenticated" USING (((( SELECT "auth"."uid"() AS "uid") = "attendee_id") AND (EXISTS ( SELECT 1
   FROM "public"."memberships"
  WHERE (("memberships"."user_id" = "auth"."uid"()) AND ("memberships"."org_id" = "attendance"."org_id"))))));



CREATE POLICY "Officers can create meetings" ON "public"."meetings" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."memberships"
  WHERE (("memberships"."user_id" = ( SELECT "auth"."uid"() AS "uid")) AND ((("memberships"."org_id" = "meetings"."org_id") AND ("memberships"."role" = ANY (ARRAY['officer'::"text", 'owner'::"text"]))) OR ("memberships"."role" = 'admin'::"text"))))));



CREATE POLICY "Officers can delete meetings" ON "public"."meetings" FOR DELETE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."memberships"
  WHERE (("memberships"."user_id" = ( SELECT "auth"."uid"() AS "uid")) AND ((("memberships"."org_id" = "meetings"."org_id") AND ("memberships"."role" = ANY (ARRAY['officer'::"text", 'owner'::"text"]))) OR ("memberships"."role" = 'admin'::"text"))))));



CREATE POLICY "Officers can update meetings" ON "public"."meetings" FOR UPDATE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."memberships"
  WHERE (("memberships"."user_id" = ( SELECT "auth"."uid"() AS "uid")) AND ((("memberships"."org_id" = "meetings"."org_id") AND ("memberships"."role" = ANY (ARRAY['officer'::"text", 'owner'::"text"]))) OR ("memberships"."role" = 'admin'::"text")))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."memberships"
  WHERE (("memberships"."user_id" = ( SELECT "auth"."uid"() AS "uid")) AND (("memberships"."role" = 'admin'::"text") OR (("memberships"."org_id" = "meetings"."org_id") AND ("memberships"."role" = ANY (ARRAY['officer'::"text", 'owner'::"text"]))))))));



CREATE POLICY "Officers can view attendance data (and admins)" ON "public"."attendance" FOR SELECT TO "authenticated" USING (((EXISTS ( SELECT 1
   FROM "public"."memberships"
  WHERE ((( SELECT "auth"."uid"() AS "uid") = "memberships"."user_id") AND ((("memberships"."org_id" = ( SELECT "meetings"."org_id"
           FROM "public"."meetings"
          WHERE ("meetings"."id" = "attendance"."meeting_id"))) AND ("memberships"."role" = ANY (ARRAY['officer'::"text", 'owner'::"text"]))) OR ("memberships"."role" = 'admin'::"text"))))) OR ((( SELECT "auth"."uid"() AS "uid") = "attendee_id") AND (EXISTS ( SELECT 1
   FROM "public"."memberships"
  WHERE (("memberships"."user_id" = "auth"."uid"()) AND ("memberships"."org_id" = "attendance"."org_id")))))));



CREATE POLICY "Owners and Admins can see audit log" ON "public"."audit_log" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."memberships"
  WHERE (("memberships"."user_id" = "auth"."uid"()) AND (("memberships"."role" = 'admin'::"text") OR (("memberships"."org_id" = "audit_log"."org_id") AND ("memberships"."role" = 'owner'::"text")))))));



CREATE POLICY "Users can view their own data + Officers can view org member li" ON "public"."memberships" FOR SELECT TO "authenticated" USING (((( SELECT "auth"."uid"() AS "uid") = "user_id") OR (EXISTS ( SELECT 1
   FROM "public"."memberships" "memberships_1"
  WHERE (("memberships_1"."user_id" = "auth"."uid"()) AND ("memberships_1"."org_id" = "memberships_1"."org_id") AND ("memberships_1"."role" = ANY (ARRAY['officer'::"text", 'owner'::"text", 'admin'::"text"])))))));



CREATE POLICY "View Active Meetings, Officers can view ALL meetings" ON "public"."meetings" FOR SELECT TO "authenticated" USING (((EXISTS ( SELECT 1
   FROM "public"."memberships"
  WHERE (("memberships"."user_id" = "auth"."uid"()) AND ((("memberships"."org_id" = "meetings"."org_id") AND ("memberships"."role" = ANY (ARRAY['officer'::"text", 'owner'::"text"]))) OR ("memberships"."role" = 'admin'::"text"))))) OR (EXISTS ( SELECT 1
   FROM "public"."memberships"
  WHERE (("memberships"."org_id" = "meetings"."org_id") AND ("memberships"."user_id" = ( SELECT "auth"."uid"() AS "uid")))))));



ALTER TABLE "public"."audit_log" ENABLE ROW LEVEL SECURITY;


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON TABLE "public"."attendance" TO "anon";
GRANT ALL ON TABLE "public"."attendance" TO "authenticated";
GRANT ALL ON TABLE "public"."attendance" TO "service_role";



GRANT ALL ON TABLE "public"."attendee" TO "anon";
GRANT ALL ON TABLE "public"."attendee" TO "authenticated";
GRANT ALL ON TABLE "public"."attendee" TO "service_role";



GRANT ALL ON TABLE "public"."audit_log" TO "anon";
GRANT ALL ON TABLE "public"."audit_log" TO "authenticated";
GRANT ALL ON TABLE "public"."audit_log" TO "service_role";



GRANT ALL ON SEQUENCE "public"."audit_log_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."audit_log_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."audit_log_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."meetings" TO "anon";
GRANT ALL ON TABLE "public"."meetings" TO "authenticated";
GRANT ALL ON TABLE "public"."meetings" TO "service_role";



GRANT ALL ON TABLE "public"."memberships" TO "anon";
GRANT ALL ON TABLE "public"."memberships" TO "authenticated";
GRANT ALL ON TABLE "public"."memberships" TO "service_role";



GRANT ALL ON TABLE "public"."organizations" TO "anon";
GRANT ALL ON TABLE "public"."organizations" TO "authenticated";
GRANT ALL ON TABLE "public"."organizations" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";







